### ISSUE TITLE
Not able to disable XPack from Docker Compose 

### ISSUE THREAD

**Issue by shreyu86** [elastic/elasticsearch-docker#127]
## Bug Description
Here is my docker-compose file:
```yaml
version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: es
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
```
on executing `docker-compose up` the resulting ES instance still has XPack upon inspecting the container I can verify that the `Env` has the values which were passed to `docker-compose.yml`
![image](https://user-images.githubusercontent.com/311217/31515841-89dd44fc-af4b-11e7-971c-582337b34159.png)

Here is some additional information:
* Docker image used : `docker.elastic.co/elasticsearch/elasticsearch:5.6.3`
* Operating System: `macOS 10.13 (17A405)`
* `docker info` 
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 43
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: EEL2:LAL3:HNHG:W7MI:HFYX:ESAL:ZZ73:V3T5:RR3F:D5VM:KLHJ:5TLV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 35
 Goroutines: 51
 System Time: 2017-10-12T19:50:36.858723896Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
* `docker inspect NAME|ID` output
* `docker-compose --version`, 
`1.16.1, build 6d1ac21`
