### ISSUE TITLE
disable security for free basic license?

### ISSUE THREAD

**Issue by agonzalezm** [elastic/elasticsearch-docker#18]
My instance expired and i have installed a free basic license but i cant login in kibana with message: Your "Basic license does not support Security. Please upgrade your license or disable Security in Elasticsearch."

I read i have to disable security using xpack.security.enabled = false on elasticsearch.yml and kibana.yml.

How can i run the elasticksearch and kibana instances disabling security? is it possible to pass it as a param?

**Comment by jarpy** [comment]
There are several ways to achieve this, including via YAML configuration files
 and by setting environment variables (which modify the command-lines of the
container processes).                                                                                                         
The general approach for these techniques is shown in the README files for [Elasticsearch][e] and [Kibana][k]. For the specific case of disabling Security, I will give some examples.

[e]: https://github.com/elastic/elasticsearch-docker/blob/5.0/README.md#configuration-options
[k]: https://github.com/elastic/kibana-docker/blob/5.0/README.md#configuration-options

The easiest way might be to use environment variables. If you are using `docker-compose`, the needed configuration could look like this:

``` yaml
---
version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.0.0
    environment: { xpack.security.enabled: 'false' }

  kibana:
    image: docker.elastic.co/kibana/kibana:5.0.0
    ports: [ '5601:5601' ]
    links: [ elasticsearch ]
    environment: { XPACK_SECURITY_ENABLED: 'false' }
```
Note the different format for the environment variables (I'd like to rationalize that in a later release).

From the basic `docker` command-line, use the `-e` flag to set environment variables. Here's a working example:
``` shell
docker run --name elasticsearch -d -e xpack.security.enabled=false docker.elastic.co/elasticsearch/elasticsearch:5.0.0
docker run -d --link elasticsearch -p5601:5601 -e XPACK_SECURITY_ENABLED=false docker.elastic.co/kibana/kibana:5.0.0
```
<sub>Elasticsearch volume settings omitted for brevity.</sub>

Alternatively, you could provide custom YAML configuration files to Elasticsearch and Kibana, either by bind-mounting, or by building images based on the offical ones, but with custom config files. Take a look at the README files if that option appeals to you.

Thanks, and Happy 'Stacking.
