### ISSUE TITLE
The user of docker.elastic.co/elasticsearch/elasticsearch:6.4.2 is root

### ISSUE THREAD

**Issue by hiroshi** [elastic/elasticsearch-docker#204]
* Docker image used: `docker.elastic.co/elasticsearch/elasticsearch:6.4.2`
* Operating System: `macOS (docker for mac)`
* `docker info` output: sorry, but I don't think it matter
* `docker inspect NAME|ID` output: sorry, but I don't think it matter
* `docker-compose --version`, if relevant
* Steps to reproduce
```sh
$ docker run --rm -ti docker.elastic.co/elasticsearch/elasticsearch:6.4.2 whoami 
root
$ docker run --rm -ti docker.elastic.co/elasticsearch/elasticsearch:5.4.1 whoami
elasticsearch
```

**Comment by hiroshi** [comment]
As a workaround of `can not run elasticsearch as root` for Kubernetes.

```yaml
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
        securityContext:
          runAsUser: 1000
        ...
```
