### ISSUE TITLE
Can't set ES_JAVA_OPTS 

### ISSUE THREAD

**Issue by pulpbill** [elastic/elasticsearch-docker#239]
This is my docker-compose:

```
nginx:
  image: nginx:alpine
  container_name: nginx
  command: nginx -g "daemon off;"
  volumes:
  - ./nginx/config/conf.d:/etc/nginx/conf.d
  ports:
    - "8080:8080"
  links:
    - kibana

elasticsearch:
  image: elasticsearch:latest
  container_name: elasticsearch
#  image: elasticsearch:2.4.6-alpine
  command: elasticsearch
# -Ees.network.host=0.0.0.0
  environment:
    ES_JAVA_OPTS: -Xms6g -Xmx6g

  volumes:
    - ./elasticsearch/storage:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  container_name: logstash
  environment:
    - "LS_JAVA_OPTS=-Xmx256m -Xms256m"

  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
    - "5044:5044"
  links:
    - elasticsearch
kibana:
  build: kibana/
  container_name: kibana
  volumes:
    - ./kibana/config:/opt/kibana/config
  ports:
    - "5601:5601"
  links:
    - elasticsearch

```

I've been trying to set jvm heap size to 6g (or anything for what matters) but couldn't, I checked previous issues, tried moving values around and same result. While running top at docker host I just got -Xms2g -Xmx2g same for /etc/elasticsearch/jvm.options file inside ES container. 
And, eventually, this container crashes due to lack of jvm heap size. That's why I'm trying to increase it. 

What am I doing worng? Thanks!
