### ISSUE TITLE
WARN transport/tcp.go:53 DNS lookup failure “elasticsearch”: lookup elasticsearch on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by karetfe** [elastic/elasticsearch-docker#240]
I am using the ElK stack to visualize the logs of my apis, using a configured docker images of elasticsearch 6 and kibana 6, I got this error after I build and run the images, it work fine the first hours, but then elasticsearch crush .

I used several time docker-compose down,docker-compose build, docker-compose up -d, It workes again but I got the same errors after some hours. I am using the same docker client and server version 17.12.0 when I try service elasticsearch ,it tell that it is not running as well as kibana service

Here the elasticsearch.yml config file of elasticsearch:

```
network.host: 0.0.0.0
transport.host: 0.0.0.0
discovery.type: single-node
discovery.zen.minimum_master_nodes: 1
xpack.ml.enabled: false
xpack.monitoring.enabled: false
xpack.security.enabled: false
xpack.graph.enabled : false
```

The Dockerfile:
`ARG ELASTIC_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}`

The docker-compose.yml file is :
```
version: '2'
services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk_backend
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  apm-server:
    build:
      context: apm/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    ports:
      - 8200:8200
    volumes:
      - ./apm/config/apm-server.yml:/usr/share/apm-server/apm-server.yml:rw
    depends_on:
      - elasticsearch
    networks:
      - elk_backend
networks:
  elk_backend:
    driver: bridge
volumes:
  data:
    driver: local
```

Expected results Elasticsearch doesn't crush
