### ISSUE TITLE
Basic Auth Error using elastic and changeme 

### ISSUE THREAD

**Issue by dbroadhurst** [elastic/elasticsearch-docker#38]
* `docker info` output:
````
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "failed to authenticate user [elastic]",
        "header": {
          "WWW-Authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
        }
      }
    ],
    "type": "security_exception",
    "reason": "failed to authenticate user [elastic]",
    "header": {
      "WWW-Authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
    }
  },
  "status": 401
}
````

* `docker-compose` version:
2

* Host OS and version:
osx

## Bug description
Then I run the docker container using 
````
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.2.2
````

I've also tried with my compose file but get the same results

````
version: "2"

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.2
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline/
      - ./logstash/config:/usr/share/logstash/config/
      - ./logstash/csv:/usr/share/logstash/csv/
    links: 
      - elastic      
````

I can curl 
````
curl -u elastic http://127.0.0.1:9200/_cat/health
````
and get an expect response.

If I use basic auth from postman or more importantly from logstash
````
    elasticsearch {
      hosts => ["http://elastic:changeme@127.0.0.0:9200/test"]
      index => "logstash-test"
      user => "elastic"
      password => "changeme"
    }
````
I get
 
````
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "failed to authenticate user [elastic]",
        "header": {
          "WWW-Authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
        }
      }
    ],
    "type": "security_exception",
    "reason": "failed to authenticate user [elastic]",
    "header": {
      "WWW-Authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
    }
  },
  "status": 401
}
````
